Networking stuff
minecraft-cursed-legacy/Plasma pull request #62
Opened 2021-04-16 08:32 UTC by BoogieMonster1O1

Not packet stuff

2021-04-16 08:33 UTC, BoogieMonster1O1 commented
also i dropped invalid mappings so ignore any rearrangements

2021-04-16 10:49 UTC, valoeghese requested changes

2021-04-16 10:49 UTC, valoeghese commented on mappings/net/minecraft/network/ClientConnection.mapping
> +	FIELD field_1284 dataOutput Ljava/io/DataOutputStream;
input and output would be more concise

2021-04-16 10:49 UTC, valoeghese commented on mappings/net/minecraft/network/ClientConnection.mapping
> +CLASS net/minecraft/class_117 net/minecraft/network/ClientConnection
ConnectionHandler

2021-04-16 10:49 UTC, valoeghese commented on mappings/net/minecraft/server/network/ServerLoginPacketHandler.mapping
> +CLASS net/minecraft/class_10 net/minecraft/server/network/ServerLoginPacketHandler
PendingConnection

2021-04-16 10:49 UTC, valoeghese commented on mappings/net/minecraft/server/network/ServerPlayPacketHandler.mapping
> +CLASS net/minecraft/class_11 net/minecraft/server/network/ServerPlayPacketHandler
ServerPlayerConnection

2021-04-16 11:02 UTC, valoeghese commented on mappings/net/minecraft/network/ClientConnection.mapping
> +CLASS net/minecraft/class_117 net/minecraft/network/ClientConnection
PacketDispatcher

2021-04-16 11:19 UTC, valoeghese commented
ok nvm wait until tomorrow or later this week

2021-04-16 20:24 UTC, valoeghese approved these changes

2021-04-16 20:24 UTC, valoeghese commented on mappings/net/minecraft/network/ClientConnection.mapping
> +CLASS net/minecraft/class_117 net/minecraft/network/ClientConnection
nvm Connection

2021-04-17 00:58 UTC, valoeghese commented
let me know whan u test it

2021-04-17 05:05 UTC, merged